version: '3.8'
services: 
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: example_pass
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
      